In [158]:
import numpy as np, matplotlib.pyplot as plt, random, math

1c

In [159]:
q = 0.4
p = 0.35
s = 0.25
total = 0
n = 100000
for _ in range(n):
    i = 10
    while i > 0:
        u = random.random()
        if u <= q:
            i -= 1
        elif u <= q + p:
            i += 1
        else:
            break
    total += i
print(total / n)


9.81047


In [160]:
e = lambda p, q, s, i: i + ((p - q) / s) * (1 - ((1 - math.sqrt(1 - 4 * p * q)) / (2 * p)) ** i)
print(e(p, q, s, 10))

9.800132482594409


2a

In [161]:
p = np.zeros((6,6))
for i in range(6):
    for j in range(6):
        if i == 0 and j == 5:
            p[i,j] = 1
        elif i != 0 and i >= j:
            p[i,j] = math.comb(i, j) * 0.1 ** (i - j) * 0.9 ** j
        else:
            p[i,j] = 0
print(p)
for i in range(6):
    print(np.sum(p[i,:]))

[[0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00]
 [1.0000e-01 9.0000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e-02 1.8000e-01 8.1000e-01 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e-03 2.7000e-02 2.4300e-01 7.2900e-01 0.0000e+00 0.0000e+00]
 [1.0000e-04 3.6000e-03 4.8600e-02 2.9160e-01 6.5610e-01 0.0000e+00]
 [1.0000e-05 4.5000e-04 8.1000e-03 7.2900e-02 3.2805e-01 5.9049e-01]]
1.0
1.0
1.0
1.0000000000000002
1.0
1.0


2b

In [162]:
A = np.array([
    [0.9-1, 0, 0, 0, 0],
    [0.18, 0.81-1, 0, 0, 0],
    [0.027, 0.243, 0.729-1, 0, 0],
    [0.0036, 0.0486, 0.2916, 0.6561-1, 0],
    [0.00045, 0.0081, 0.0729, 0.32805, 0.59049-1]
])
b = -1 * np.ones(5)
print(np.linalg.solve(A, b))



[10.         14.73684211 17.90056322 20.27337819 22.17162266]


2c

In [163]:
A = np.array([
    [-1, 0.1, 0.01, 0.001, 0.0001, 0.00001],
    [0, 0.9-1, 0.18, 0.027, 0.0036, 0.00045],
    [0, 0, 0.81-1, 0.243, 0.0486, 0.0081],
    [0, 0, 0, 0.729-1, 0.2916,  0.0729],
    [0, 0, 0, 0, 0.6561-1, 0.32805],
    [1, 0, 0, 0, 0, 0.59049-1]
])
b = np.array([0, 0, 0, 0, 0, 0])
res = np.linalg.solve(A, b)
print(res)

[-0.  0.  0. -0. -0.  0.]


In [164]:
A = np.array([
    [-1, 0.1, 0.01, 0.001, 0.0001, 0.00001],
    [0, 0.9-1, 0.18, 0.027, 0.0036, 0.00045],
    [0, 0, 0.81-1, 0.243, 0.0486, 0.0081],
    [0, 0, 0, 0.729-1, 0.2916,  0.0729],
    [0, 0, 0, 0, 0.6561-1, 0.32805],
    [1, 1, 1, 1, 1, 1]
])
b = np.array([0, 0, 0, 0, 0, 1])
res = np.linalg.solve(A, b)
print(res)

[0.04315624 0.40960542 0.20480677 0.13651855 0.10052797 0.10538506]


In [165]:
A = np.array([
    [-1, 0.1, 0.01, 0.001, 0.0001, 0.00001],
    [0, 0.9-1, 0.18, 0.027, 0.0036, 0.00045],
    [0, 0, 0.81-1, 0.243, 0.0486, 0.0081],
    [1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0.6561-1, 0.32805],
    [1, 0, 0, 0, 0, 0.59049-1]
])
b = np.array([0, 0, 0, 1, 0, 0])
res = np.linalg.solve(A, b)
print(res)

[0.04315624 0.40960542 0.20480677 0.13651855 0.10052797 0.10538506]
